server:
  servlet:
    contextPath: /file
    port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=testdb;encrypt=true;trustServerCertificate=true;
    username: sa
    password: yourStrong(!)Password